-- MySQL Script generated by MySQL Workbench
-- Wed Jan  2 03:59:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema educafro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema educafro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `educafro` DEFAULT CHARACTER SET utf8 ;
USE `educafro` ;

-- -----------------------------------------------------
-- Table `educafro`.`cadastros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cadastros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lembrar` TINYINT(4) NULL DEFAULT NULL,
  `password` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `first_name` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `last_name` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `nome` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rg` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cpf` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cep` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `registrosid` INT(11) NULL DEFAULT NULL,
  `codigoid` INT(11) NULL DEFAULT NULL,
  `perfisid` INT(11) NULL DEFAULT NULL,
  `contatosid` INT(11) NULL DEFAULT NULL,
  `ddd` VARCHAR(6) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `numero` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rolesid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `rg` (`rg` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `perfisid` (`perfisid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`codigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`codigos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ativacao` TINYINT(4) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1029
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`perfis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `rg` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cpf` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `cep` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endereco` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endereconum` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `bairro` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cidade` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `estado` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`contatos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfis_id` INT(11) NOT NULL,
  `ddd` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `numero` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `falarcom` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aparelho` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'aparelho principal, fixo ou celular',
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `type` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `perfis_id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `fk_contatos_perfis1_idx` (`perfis_id` ASC),
  CONSTRAINT `fk_contatos_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'aqui sera salvo todos os cursos ofertados na educafro, momentaneamente sera Itafro, MedAfro e o Tecnoafro, caso o curso for segmentado, mantem o mesmo nome e altera o titulo expl: nome->Tecnoafro e titulo-> SEO ou nome->Tecnoafro e titulo-> Suporte técnico, Tabela cursos baseada na metodologia da USP -> https://uspdigital.usp.br/jupiterweb/listarGradeCurricular?codcg=27&codcur=27531&codhab=4&tipo=N&print=true',
  `logo` VARCHAR(240) NULL,
  `nome` VARCHAR(40) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `img` VARCHAR(240) NULL,
  `descricao` TINYTEXT NULL,
  `informacoes` TEXT NULL,
  `nivel` ENUM('Reforço', 'Preparatório', 'Profissionalizante', 'Pós-Graduação') NULL,
  `tipo` ENUM('Encerrado', 'Presencial', 'Online', 'Presencial e Online') NULL,
  `vaga` INT NULL,
  `carga_horaria` INT NULL,
  `prox_turma` DATE NULL,
  `objetivo` TINYTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`disciplinas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'método de disciplina baseado na USP, https://uspdigital.usp.br/jupiterweb/obterDisciplina?sgldis=4302111&codcur=43021&codhab=101',
  `cursos_id` INT NOT NULL,
  `nome` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `icon` VARCHAR(250) NULL DEFAULT NULL,
  `descricao` TINYTEXT NOT NULL,
  `credito_aula` INT NULL,
  `credito_trabalho` INT NULL,
  `carga_horaria_total` INT NULL,
  `tipo` ENUM('Mensal', 'Bimestral', 'Trimestral', 'Semestral', 'Anual') NULL,
  `ativacao` DATE NULL,
  `objetivos` TEXT NULL,
  `programa_resumido` VARCHAR(30) NULL,
  `programa` TEXT NULL,
  `avaliacao` SET('Método', 'Critério', 'Recuperação') NULL,
  `metodo` TINYTEXT NULL,
  `criterio` TINYTEXT NULL,
  `recuperacao` TINYTEXT NULL,
  `bibliografia` TEXT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `cursos_id`),
  INDEX `fk_diciplinas_cursos1_idx` (`cursos_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_diciplinas_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`registros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cpf` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `registros` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `perfis_id` INT(11) NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `google` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `oauth_provider` ENUM('', 'Facebook', 'Google', 'Facebook e Google') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `oauth_uid` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `first_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `last_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `gender` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `locale` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cover` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `photo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `photo_dir` VARCHAR(255) NULL,
  `photo_size` INT(11) NULL,
  `photo_type` VARCHAR(255) NULL,
  `link` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `type` ENUM('Inativo', 'Presencial', 'Online') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created` TIMESTAMP NULL DEFAULT NULL,
  `modified` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `perfis_id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `fk_users_perfis1_idx` (`perfis_id` ASC),
  CONSTRAINT `fk_users_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`regras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`regras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `regra` ENUM("Admin", "Super Usuario", "Voluntario", "Docente", "Discente") CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ativo` TINYINT(2) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_roles_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `educafro`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`upload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`upload` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'esta Tabela foi gerada com o intuito de solucionar caso o cadastrado não possa ou não esteja próximo a uma sede da educafro,ele fará o upload da documentação pessoal necessária para valida-lo como aluno, através de análise humana ou inteligência artificial. ',
  `perfis_id` INT(11) NOT NULL,
  `arq_rg` VARCHAR(250) NULL,
  `arq_cpf` VARCHAR(250) NULL,
  `arq_endereco` VARCHAR(250) NULL,
  `arq_clt1` VARCHAR(250) NULL,
  `arq_clt2` VARCHAR(250) NULL,
  `arq_clt3` VARCHAR(250) NULL,
  `arq_clt4` VARCHAR(250) NULL,
  `arq_clt5` VARCHAR(250) NULL,
  `arq_pis_pasep` VARCHAR(250) NULL,
  PRIMARY KEY (`id`, `perfis_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_upload_perfis_idx` (`perfis_id` ASC),
  CONSTRAINT `fk_upload_perfis`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`users_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`users_cursos` (
  `users_id` INT(11) NOT NULL,
  `cursos_id` INT NOT NULL,
  `progresso` ENUM('Desvinculado', 'Aguardando', 'Habilitado') NULL COMMENT 'USERS_ID.NOME esta PROGRESSO cadastrado como TIPO  no curso CURSOS_ID.NOME, SITUACAO em todas as materias',
  `tipo` ENUM('Discente', 'Docente', 'Coordenador') NULL COMMENT 'USERS_ID.NOME esta PROGRESSO cadastrado como TIPO  no curso CURSOS_ID.NOME, SITUACAO em todas as materias',
  `situacao` ENUM('Bloqueado', 'Cursando', 'Aprovado', 'Desaprovado', 'Ministrando') NULL COMMENT 'USERS_ID.NOME esta PROGRESSO cadastrado como TIPO  no curso CURSOS_ID.NOME, SITUACAO em todas as materias.',
  `media` INT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`users_id`, `cursos_id`),
  INDEX `fk_users_has_cursos_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_users_has_cursos_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_cursos_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `educafro`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `educafro`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`temas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disciplinas_id` INT(11) NOT NULL,
  `nome` VARCHAR(60) NULL,
  `descricao` TINYTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `disciplinas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_temas_disciplinas1_idx` (`disciplinas_id` ASC),
  CONSTRAINT `fk_temas_disciplinas1`
    FOREIGN KEY (`disciplinas_id`)
    REFERENCES `educafro`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`subtemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`subtemas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'baseado no processo do descomplica',
  `temas_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TINYTEXT NULL,
  `carga_horaria` INT NULL,
  `author` INT NULL COMMENT 'id do usuario que criou este subtema',
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `temas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_subtema_temas1_idx` (`temas_id` ASC),
  CONSTRAINT `fk_subtema_temas1`
    FOREIGN KEY (`temas_id`)
    REFERENCES `educafro`.`temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`aulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subtemas_id` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `subtitulo` TINYTEXT NULL,
  `descricao` TEXT NULL,
  `aviso` TEXT NULL,
  `videoaula` VARCHAR(250) NULL,
  `material_apoio` VARCHAR(250) NULL,
  `bibliografia` TINYTEXT NULL,
  `entregar_trabalho` DATETIME NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `subtemas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_aulas_subtemas1_idx` (`subtemas_id` ASC),
  CONSTRAINT `fk_aulas_subtemas1`
    FOREIGN KEY (`subtemas_id`)
    REFERENCES `educafro`.`subtemas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `sobre` TINYTEXT NULL,
  `disponibilidade` SET('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sabado') NULL COMMENT 'disponibilidade para responder dúvidas online ou via redes sociais',
  `horas_diarias` INT NULL COMMENT 'ver disponibilidade',
  `inicio_aula` TIME NULL COMMENT 'ver disponibilidade',
  `fim_aula` TIME NULL COMMENT 'ver disponibilidade',
  `linkedin_perfil` VARCHAR(100) NULL,
  `facebook_perfil` VARCHAR(100) NULL,
  `twiter_perfil` VARCHAR(100) NULL,
  `lattes_curriculo` VARCHAR(100) NULL,
  `curriculo` VARCHAR(250) NULL,
  `nota_discente` INT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_professores_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_professores_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `educafro`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`particularidade_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`particularidade_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Nesta Tabela será salvo os dados JSON de cada usuário, e devido a um bug precisei deixar os datatype em TEXT ao invés de JSON',
  `users_id` INT(11) NOT NULL,
  `aulas_id` INT NOT NULL,
  `upload_id` INT NOT NULL,
  `perfis_id` INT(11) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  `contatos_id` INT(11) NOT NULL,
  `chave_token` VARCHAR(255) NULL,
  `sessao` TEXT NULL,
  `log` TEXT NULL,
  `configuracao` TEXT NULL,
  `sistema` TEXT NULL,
  `dados_gerado` TEXT NULL,
  `dados_arquivados` TEXT NULL,
  `dados_apagados` TEXT NULL,
  `dados_logica` TEXT NULL,
  `metadados` TEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `users_id`, `aulas_id`, `upload_id`, `perfis_id`, `roles_id`, `contatos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_particularidades_users1_idx` (`users_id` ASC),
  INDEX `fk_particularidades_aulas1_idx` (`aulas_id` ASC),
  INDEX `fk_particularidades_upload1_idx` (`upload_id` ASC),
  INDEX `fk_particularidades_perfis1_idx` (`perfis_id` ASC),
  INDEX `fk_particularidades_roles1_idx` (`roles_id` ASC),
  INDEX `fk_particularidades_contatos1_idx` (`contatos_id` ASC),
  CONSTRAINT `fk_particularidades_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `educafro`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_particularidades_aulas1`
    FOREIGN KEY (`aulas_id`)
    REFERENCES `educafro`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_particularidades_upload1`
    FOREIGN KEY (`upload_id`)
    REFERENCES `educafro`.`upload` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_particularidades_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_particularidades_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `educafro`.`regras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_particularidades_contatos1`
    FOREIGN KEY (`contatos_id`)
    REFERENCES `educafro`.`contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`particularidade_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`particularidade_sistema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `particularidade_sistemacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
