-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 17:11:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema educafro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema educafro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `educafro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `educafro` ;

-- -----------------------------------------------------
-- Table `educafro`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`administradores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `regras_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `regras_id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_administradores_regras1_idx` (`regras_id` ASC) VISIBLE,
  INDEX `fk_administradores_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_administradores_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_administradores_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`administradores_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`administradores_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`administradores_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`administradores_tokens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Esta tabela é reponsável por armazenar a senha de permissão pública de cada usuário. Permitindo que ao usá-la em outra sessão o inquilino receba tal privilégio para executar a devida função.  ',
  `administradores_id` INT(11) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `instancia` VARCHAR(255) NULL DEFAULT NULL,
  `ip_restricao` VARCHAR(255) NULL DEFAULT NULL,
  `info` MEDIUMTEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `administradores_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_administradores_token_administradores1_idx` (`administradores_id` ASC) VISIBLE,
  CONSTRAINT `fk_administradores_token_administradores1`
    FOREIGN KEY (`administradores_id`)
    REFERENCES `educafro`.`administradores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'aqui sera salvo todos os cursos ofertados na educafro, momentaneamente sera Itafro, MedAfro e o Tecnoafro, caso o curso for segmentado, mantem o mesmo nome e altera o titulo expl: nome->Tecnoafro e titulo-> SEO ou nome->Tecnoafro e titulo-> Suporte técnico, Tabela cursos baseada na metodologia da USP -> https://uspdigital.usp.br/jupiterweb/listarGradeCurricular?codcg=27&codcur=27531&codhab=4&tipo=N&print=true',
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `nome` VARCHAR(32) NULL DEFAULT NULL,
  `titulo` VARCHAR(128) NULL DEFAULT NULL,
  `img` VARCHAR(256) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `info` TEXT NULL DEFAULT NULL,
  `nivel` ENUM('Outros', 'Reforço', 'Pré-vestibular', 'Profissionalizante', 'Pós-Graduação') NULL DEFAULT NULL,
  `tipo` ENUM('Encerrado', 'Em Breve', 'Presencial', 'Online', 'Presencial e Online') NULL DEFAULT NULL,
  `vagas` INT(4) NULL DEFAULT NULL,
  `carga_horaria` VARCHAR(16) NULL DEFAULT NULL,
  `prox_turma` DATE NULL DEFAULT NULL,
  `objetivo` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `modificadores_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `modificadores_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursos_modificadores1_idx` (`modificadores_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_modificadores1`
    FOREIGN KEY (`modificadores_id`)
    REFERENCES `educafro`.`modificadores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos_secoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos_secoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cursos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursos_secoes_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_secoes_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`docentes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `regras_id` INT(11) NOT NULL,
  `cursos_secoes_id` INT(11) NOT NULL,
  `tipo` ENUM('Online', 'Presencial') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`, `regras_id`, `cursos_secoes_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_professores_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_professores_regras1_idx` (`regras_id` ASC) VISIBLE,
  INDEX `fk_professores_cursos_secoes1_idx` (`cursos_secoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_professores_cursos_secoes1`
    FOREIGN KEY (`cursos_secoes_id`)
    REFERENCES `educafro`.`cursos_secoes` (`id`),
  CONSTRAINT `fk_professores_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_professores_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos_modulos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cursos_id` INT(11) NOT NULL,
  `grupos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`, `grupos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursos_modulos_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  INDEX `fk_cursos_modulos_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_modulos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`),
  CONSTRAINT `fk_cursos_modulos_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`disciplinas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'método de disciplina baseado na USP, https://uspdigital.usp.br/jupiterweb/obterDisciplina?sgldis=4302111&codcur=43021&codhab=101',
  `cursos_modulos_id` INT(11) NOT NULL,
  `cursos_modulos_cursos_id` INT(11) NOT NULL,
  `nome` VARCHAR(64) NULL DEFAULT NULL,
  `icon` VARCHAR(256) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `credito_aula` INT(11) NULL DEFAULT NULL,
  `credito_trabalho` INT(11) NULL DEFAULT NULL,
  `carga_horaria_total` INT(11) NULL DEFAULT NULL,
  `tipo` ENUM('Semanal', 'Mensal', 'Bimestral', 'Trimestral', 'Semestral', 'Anual') NULL DEFAULT NULL,
  `ativar` DATE NULL DEFAULT NULL,
  `objetivos` TEXT NULL DEFAULT NULL,
  `programa_resumido` VARCHAR(64) NULL DEFAULT NULL,
  `programa` TEXT NULL DEFAULT NULL,
  `avaliacao` SET('Método', 'Critério', 'Recuperação') NULL DEFAULT NULL,
  `metodo` TEXT NULL DEFAULT NULL,
  `criterio` TEXT NULL DEFAULT NULL,
  `recuperacao` TEXT NULL DEFAULT NULL,
  `bibliografia` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `modificadores_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_modulos_id`, `cursos_modulos_cursos_id`, `modificadores_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_disciplinas_cursos_modulos1_idx` (`cursos_modulos_id` ASC, `cursos_modulos_cursos_id` ASC) VISIBLE,
  INDEX `fk_disciplinas_modificadores1_idx` (`modificadores_id` ASC) VISIBLE,
  CONSTRAINT `fk_disciplinas_cursos_modulos1`
    FOREIGN KEY (`cursos_modulos_id` , `cursos_modulos_cursos_id`)
    REFERENCES `educafro`.`cursos_modulos` (`id` , `cursos_id`),
  CONSTRAINT `fk_disciplinas_modificadores1`
    FOREIGN KEY (`modificadores_id`)
    REFERENCES `educafro`.`modificadores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`temas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `disciplinas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `disciplinas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_temas_disciplinas1_idx` (`disciplinas_id` ASC) VISIBLE,
  CONSTRAINT `fk_temas_disciplinas1`
    FOREIGN KEY (`disciplinas_id`)
    REFERENCES `educafro`.`disciplinas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`subtemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`subtemas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `temas_id` INT(11) NOT NULL,
  `docentes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `temas_id`, `docentes_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_subtemas_temas1_idx` (`temas_id` ASC) VISIBLE,
  INDEX `fk_subtemas_docentes1_idx` (`docentes_id` ASC) VISIBLE,
  CONSTRAINT `fk_subtemas_docentes1`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `educafro`.`docentes` (`id`),
  CONSTRAINT `fk_subtemas_temas1`
    FOREIGN KEY (`temas_id`)
    REFERENCES `educafro`.`temas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`aulas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subtemas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `subtemas_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_aula_subtemas1_idx` (`subtemas_id` ASC) VISIBLE,
  CONSTRAINT `fk_aula_subtemas1`
    FOREIGN KEY (`subtemas_id`)
    REFERENCES `educafro`.`subtemas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`categorizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`categorizacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcategorizacao_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`categorizacao_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`categorizacao_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categorizacao_id` INT(11) NOT NULL,
  `categorizacao_eventos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `categorizacao_id`, `categorizacao_eventos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_categorizacao_info_categorizacao1_idx` (`categorizacao_id` ASC, `categorizacao_eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_categorizacao_info_categorizacao1`
    FOREIGN KEY (`categorizacao_id`)
    REFERENCES `educafro`.`categorizacao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`codigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`codigos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigos_tags_id` INT(11) NOT NULL,
  `codigo` VARCHAR(100) NULL DEFAULT NULL,
  `ativacao` ENUM('Desativado', 'Ativado', 'Inválido') NULL DEFAULT NULL COMMENT 'Este código está :',
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `codigos_tags_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_codigos_codigos_tags1_idx` (`codigos_tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_codigos_codigos_tags1`
    FOREIGN KEY (`codigos_tags_id`)
    REFERENCES `educafro`.`codigos_tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos_historico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cursos_secoes_id` INT(11) NOT NULL,
  `cursos_secoes_cursos_id` INT(11) NOT NULL,
  `log_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_secoes_id`, `cursos_secoes_cursos_id`, `log_id`),
  UNIQUE INDEX `idcursos_historico_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursos_historico_cursos_secoes1_idx` (`cursos_secoes_id` ASC, `cursos_secoes_cursos_id` ASC) VISIBLE,
  INDEX `fk_cursos_historico_log1_idx` (`log_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_historico_cursos_secoes1`
    FOREIGN KEY (`cursos_secoes_id` , `cursos_secoes_cursos_id`)
    REFERENCES `educafro`.`cursos_secoes` (`id` , `cursos_id`),
  CONSTRAINT `fk_cursos_historico_log1`
    FOREIGN KEY (`log_id`)
    REFERENCES `educafro`.`log` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`cursos_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`cursos_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cursos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cursos_info_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_info_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`discentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`discentes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `regras_id` INT(11) NOT NULL,
  `cursos_modulos_id` INT(11) NOT NULL,
  `tipo` ENUM('Online', 'Presencial') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`, `regras_id`, `cursos_modulos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_alunos_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_alunos_regras1_idx` (`regras_id` ASC) VISIBLE,
  INDEX `fk_alunos_cursos_modulos1_idx` (`cursos_modulos_id` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_cursos_modulos1`
    FOREIGN KEY (`cursos_modulos_id`)
    REFERENCES `educafro`.`cursos_modulos` (`id`),
  CONSTRAINT `fk_alunos_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_alunos_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`eventos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `modificadores_id` INT(11) NOT NULL,
  `categorizacao_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `modificadores_id`, `categorizacao_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_eventos_modificadores1_idx` (`modificadores_id` ASC) VISIBLE,
  INDEX `fk_eventos_categorizacao1_idx` (`categorizacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_eventos_categorizacao1`
    FOREIGN KEY (`categorizacao_id`)
    REFERENCES `educafro`.`categorizacao` (`id`),
  CONSTRAINT `fk_eventos_modificadores1`
    FOREIGN KEY (`modificadores_id`)
    REFERENCES `educafro`.`modificadores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_administradores` (
  `grupos_id` INT(11) NOT NULL,
  `administradores_id` INT(11) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`grupos_id`, `administradores_id`),
  INDEX `fk_grupos_de_administradores_administradores1_idx` (`administradores_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_administradores_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_administradores_administradores1`
    FOREIGN KEY (`administradores_id`)
    REFERENCES `educafro`.`administradores` (`id`),
  CONSTRAINT `fk_grupos_de_administradores_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_discentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_discentes` (
  `grupos_id` INT(11) NOT NULL,
  `discentes_id` INT(11) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`grupos_id`, `discentes_id`),
  INDEX `fk_grupos_de_discentes_discentes1_idx` (`discentes_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_discentes_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_discentes_discentes1`
    FOREIGN KEY (`discentes_id`)
    REFERENCES `educafro`.`discentes` (`id`),
  CONSTRAINT `fk_grupos_de_discentes_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_docentes` (
  `grupos_id` INT(11) NOT NULL,
  `docentes_id` INT(11) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`grupos_id`, `docentes_id`),
  INDEX `fk_grupos_de_docentes_docentes1_idx` (`docentes_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_docentes_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_docentes_docentes1`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `educafro`.`docentes` (`id`),
  CONSTRAINT `fk_grupos_de_docentes_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`outros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`outros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `regras_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `regras_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_outros_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_outros_regras1_idx` (`regras_id` ASC) VISIBLE,
  CONSTRAINT `fk_outros_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_outros_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_outros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_outros` (
  `grupos_id` INT(11) NOT NULL,
  `outros_id` INT(11) NOT NULL,
  PRIMARY KEY (`grupos_id`, `outros_id`),
  INDEX `fk_grupos_de_outros_outros1_idx` (`outros_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_outros_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_outros_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`),
  CONSTRAINT `fk_grupos_de_outros_outros1`
    FOREIGN KEY (`outros_id`)
    REFERENCES `educafro`.`outros` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`super_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`super_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `regras_id` INT(11) NOT NULL,
  `regras_regras_niveis_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `regras_id`, `regras_regras_niveis_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_super_usuarios_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_super_usuarios_regras1_idx` (`regras_id` ASC, `regras_regras_niveis_id` ASC) VISIBLE,
  CONSTRAINT `fk_super_usuarios_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_super_usuarios_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_super_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_super_usuarios` (
  `grupos_id` INT(11) NOT NULL,
  `super_usuarios_id` INT(11) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`grupos_id`, `super_usuarios_id`),
  INDEX `fk_grupos_de_super_usuarios_super_usuarios1_idx` (`super_usuarios_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_super_usuarios_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_super_usuarios_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`),
  CONSTRAINT `fk_grupos_de_super_usuarios_super_usuarios1`
    FOREIGN KEY (`super_usuarios_id`)
    REFERENCES `educafro`.`super_usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`voluntarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `regras_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `regras_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_voluntarios_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_voluntarios_regras1_idx` (`regras_id` ASC) VISIBLE,
  CONSTRAINT `fk_voluntarios_regras1`
    FOREIGN KEY (`regras_id`)
    REFERENCES `educafro`.`regras` (`id`),
  CONSTRAINT `fk_voluntarios_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_de_voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_de_voluntarios` (
  `grupos_id` INT(11) NOT NULL,
  `voluntarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`grupos_id`, `voluntarios_id`),
  INDEX `fk_grupos_de_voluntarios_voluntarios1_idx` (`voluntarios_id` ASC) VISIBLE,
  INDEX `fk_grupos_de_voluntarios_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_de_voluntarios_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`),
  CONSTRAINT `fk_grupos_de_voluntarios_voluntarios1`
    FOREIGN KEY (`voluntarios_id`)
    REFERENCES `educafro`.`voluntarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_historico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `log_id` INT(11) NOT NULL,
  `grupos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `log_id`, `grupos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_grupos_historico_log1_idx` (`log_id` ASC) VISIBLE,
  INDEX `fk_grupos_historico_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_historico_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`),
  CONSTRAINT `fk_grupos_historico_log1`
    FOREIGN KEY (`log_id`)
    REFERENCES `educafro`.`log` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `grupos_id`),
  UNIQUE INDEX `idgrupos_info_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_grupos_info_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_info_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`grupos_secoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`grupos_secoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `grupos_id`),
  UNIQUE INDEX `idgrupos_secoes_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_grupos_secoes_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_secoes_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `educafro`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`perfis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`perfis_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`perfis_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfis_id` INT(11) NOT NULL,
  `perfis_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `perfis_id`, `perfis_user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_perfis_info_perfis1_idx` (`perfis_id` ASC, `perfis_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfis_info_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`perfis_preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`perfis_preferencias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfis_id` INT(11) NOT NULL,
  `perfis_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `perfis_id`, `perfis_user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_perfis_preferencias_perfis1_idx` (`perfis_id` ASC, `perfis_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfis_preferencias_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`perfis_upload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`perfis_upload` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `perfis_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `perfis_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_perfis_upload_perfis1_idx` (`perfis_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfis_upload_perfis1`
    FOREIGN KEY (`perfis_id`)
    REFERENCES `educafro`.`perfis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`regras_hierarquias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`regras_hierarquias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `regras_permicao_crud_id` INT(11) NOT NULL,
  `modificadores_id` INT(11) NOT NULL,
  `hierarquia` INT(11) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `regras_permicao_crud_id`, `modificadores_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_regras_hierarquias_regras_permicao_crud1_idx` (`regras_permicao_crud_id` ASC) VISIBLE,
  INDEX `fk_regras_hierarquias_modificadores1_idx` (`modificadores_id` ASC) VISIBLE,
  CONSTRAINT `fk_regras_hierarquias_modificadores1`
    FOREIGN KEY (`modificadores_id`)
    REFERENCES `educafro`.`modificadores` (`id`),
  CONSTRAINT `fk_regras_hierarquias_regras_permicao_crud1`
    FOREIGN KEY (`regras_permicao_crud_id`)
    REFERENCES `educafro`.`regras_permicao_crud` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`super_usuarios_acoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`super_usuarios_acoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `super_usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `super_usuarios_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_administradores_acoes_copy1_super_usuarios1_idx` (`super_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_administradores_acoes_copy1_super_usuarios1`
    FOREIGN KEY (`super_usuarios_id`)
    REFERENCES `educafro`.`super_usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`super_usuarios_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`super_usuarios_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`super_usuarios_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`super_usuarios_token` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Esta tabela é reponsável por armazenar a senha de permissão pública de cada usuário. Permitindo que ao usá-la em outra sessão o inquilino receba tal privilégio para executar a devida função.  ',
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `instancia` VARCHAR(255) NULL DEFAULT NULL,
  `ip_restricao` VARCHAR(255) NULL DEFAULT NULL,
  `info` MEDIUMTEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `super_usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `super_usuarios_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_super_usuarios_token_super_usuarios1_idx` (`super_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_super_usuarios_token_super_usuarios1`
    FOREIGN KEY (`super_usuarios_id`)
    REFERENCES `educafro`.`super_usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`tags_phinxlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`tags_phinxlog` (
  `version` BIGINT(20) NOT NULL,
  `migration_name` VARCHAR(100) NULL DEFAULT NULL,
  `start_time` TIMESTAMP NULL DEFAULT NULL,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  `breakpoint` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educafro`.`tags_tagged`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`tags_tagged` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tag_id` INT(11) NOT NULL,
  `fk_id` INT(11) NOT NULL,
  `fk_model` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_id` (`tag_id` ASC, `fk_id` ASC, `fk_model` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educafro`.`tags_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`tags_tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `namespace` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `counter` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC, `namespace` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educafro`.`user_historico_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`user_historico_senha` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_historico_senha_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_historico_senha_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`user_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `user_infocol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_info_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_info_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`user_inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`user_inscricoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `cursos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `cursos_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_inscricoes_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_inscricoes_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_inscricoes_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `educafro`.`cursos` (`id`),
  CONSTRAINT `fk_user_inscricoes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`user_preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`user_preferencias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_preferencias_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_preferencias_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `educafro`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `educafro`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modificadores_id` INT NOT NULL,
  `tags_tags_id` INT NOT NULL COMMENT 'esta tabela foi gerada com migrations, do plugin Tags, e a gestão por ele também',
  `tags_tagged_id` INT NOT NULL,
  `lista` JSON NULL COMMENT '[quantidade,{referenciaID, modificadores_id, datetime}]',
  PRIMARY KEY (`id`, `modificadores_id`, `tags_tags_id`, `tags_tagged_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tags_modificadores1_idx` (`modificadores_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`notificacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT 'todas as notificações emitidas ao receptor user_id',
  `nao_visualizadas` INT NULL,
  `instancias` JSON NULL COMMENT '[{nome_do_model_emissor:[{ emissorID:[{ datetime:[titulo, msg_completa, msg_html, msg_pequena, msg_format, data_criada ], contextoURL, contextoURI, contextoNOME, eventos_id, tags_id1,tags_id2, tags_id3, visualizada:false, data_visualizada}] }] }]',
  `tempo_medio_resposta` INT NULL COMMENT 'data_criada - data-visualizada de todas as notificações.instancias onde visualizadas:true',
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_notificacoes_user1_idx` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`voluntarios_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`voluntarios_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NULL,
  `instancia` VARCHAR(255) NULL,
  `ip_restricao` VARCHAR(255) NULL,
  `info` MEDIUMTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educafro`.`docentes_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `educafro`.`docentes_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NULL,
  `senhas` JSON NULL COMMENT '[{senha_criptografada:[ senha_tokenID, regras_id, status:[desativado:false, ativado:true, invalido:false, suspeito:false], data_criada, data_modificada ]}]  senha_tokenID => data_criada .´_´. data_modifcada',
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `docentes_id` INT NOT NULL,
  `docentes_user_id` INT NOT NULL,
  `docentes_regras_id` INT NOT NULL,
  `docentes_cursos_secoes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `docentes_id`, `docentes_user_id`, `docentes_regras_id`, `docentes_cursos_secoes_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_docentes_token_docentes1_idx` (`docentes_id` ASC, `docentes_user_id` ASC, `docentes_regras_id` ASC, `docentes_cursos_secoes_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
